### ISSUE TITLE
Add Option to create new  Empty Project 

### ISSUE THREAD

**Issue by Meghdut-Mandal** [jonatan-kazmierczak/class-visualizer#1]
On clicking the new Project Button a Template project is created. The template should be present in a separate MenuItem

**Comment by jonatan-kazmierczak** [comment]
Hi Meghdut,
There is no specific "template project".
The tool requires some class to be selected in Relations Diagram, Preview and Browser.
This class has to be loaded and processed and it must be always available - so it must be part of JDK/JRE.
`AccessibleObject` is chosen for this purpose, but maybe you could suggest another/better choices (with explanation, why are they better).

**About `New Project` menu item**
please provide the following required info
- expected behaviour  
- current behaviour - how does it deviate from expected behaviour

**About the suggested new menu item**
please provide the following required info
- suggested name
- expected behaviour

Thanks!

**Comment by Meghdut-Mandal** [comment]
The expected behaviour of any "New Project” option on any present day Editors, or Tools is a blank empty project having nothing in it. The tool should simply wait for the user to load a Class Path .For example the user can directly drag and drop a jar file or  a folder.
The Tool is not expected to  have such requirement, that always a class should be selected.
Suggestion for new menu Item 
•	Name:- Examples 
•	Expected behaviour:- Show a short list of classes in JDK/ JRE that can be opened
Instead of AccessibleObject  a more frequently and commonly  used class such as BufferedReader could be used. And Almost every developer familiar with   the content, Classes it extends.

**Comment by jonatan-kazmierczak** [comment]
Thanks!
It would be helpful, if you could structure the input.

**Reported wrong behaviour of `New Project` menu item**
> The expected behaviour of any "New Project” option on any present day Editors, or Tools is a blank empty project having nothing in it.

That's often not the case in the software engineering world:
i.e., new Gradle Java application project and new Ionic application create app skeleton.
The same happens here.

> The Tool is not expected to have such requirement, that always a class should be selected.

Having always some item selected is a designed and fully expected behaviour. You can find it in many browsers.

**Suggested new feature - `Examples` menu item**
> Instead of AccessibleObject a more frequently and commonly used class such as BufferedReader could be used.

As for examples - agree. Java Collection Framework contains even more commonly used classes - so I'd rather suggest choosing something from them.

You are very much welcomed to implement this feature, if it is really important to you.

**Suggested new drag&drop feature**
> For example the user can directly drag and drop a jar file or a folder.

You are very much welcomed to implement this feature, if it is really important to you.

**Comment by jonatan-kazmierczak** [comment]
This issue has unclear scope.
Please keep one precise topic item (defect, enhancement) per issue.
